# Generated by Django 3.2.6 on 2021-08-11 18:25

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('puput', '0006_auto_20210803_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrypage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.CharBlock(required=False))], template='puput/blocks/captioned-image.html')), ('embed', wagtail.core.blocks.URLBlock(template='home/partials/embed.html'))]),
        ),
    ]
