# Generated by Django 3.2.6 on 2021-09-15 23:36

from django.db import migrations
import puput.abstracts
import wagtail.contrib.table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('puput', '0009_alter_entrypage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrypage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title', template='puput/blocks/heading.html')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('animation', puput.abstracts.AnimationBlock(icon='media')), ('table', wagtail.contrib.table_block.blocks.TableBlock(template='puput/blocks/table.html')), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.CharBlock(required=False))], template='puput/blocks/captioned_image.html')), ('embed', wagtail.core.blocks.URLBlock(template='home/partials/embed.html'))]),
        ),
    ]
